// <auto-generated />
using System;
using EcommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502042431_AddCartItems")]
    partial class AddCartItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApi.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBuyer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcommerceApi.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium Apple products",
                            IsActive = true,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electronics brand",
                            IsActive = true,
                            Name = "Rangs Electronics"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gaming accessories",
                            IsActive = true,
                            Name = "Havit"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Samsung Electronics",
                            IsActive = true,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sony Electronics",
                            IsActive = true,
                            Name = "Sony"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dell Technologies",
                            IsActive = true,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dyson Home Appliances",
                            IsActive = true,
                            Name = "Dyson"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Garmin Wearables",
                            IsActive = true,
                            Name = "Garmin"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Logitech Peripherals",
                            IsActive = true,
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "General products",
                            IsActive = true,
                            Name = "Generic"
                        });
                });

            modelBuilder.Entity("EcommerceApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EcommerceApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ColorImages")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Colors")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DefaultImage")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("FastDelivery")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FreeDelivery")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasPromo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("UserId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 10,
                            Category = "Home Appliances",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1585515320310-259814833e62?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1585515320310-259814833e62?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&q=80",
                            Description = "High-performance portable electric grinder suitable for home use.",
                            DiscountPercent = 12,
                            DiscountedPrice = 777m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Portable Electric Grinder Maker",
                            Price = 888m,
                            Quantity = 50,
                            Rating = 1m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 10,
                            Category = "Health & Sports",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&q=80",
                            Description = "Foldable motorised treadmill for home workouts. Ultra-silent motor.",
                            DiscountPercent = 11,
                            DiscountedPrice = 888m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Indoor Steel Adjustable Silent Treadmill",
                            Price = 999m,
                            Quantity = 20,
                            Rating = 4m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Category = "Televisions",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400&q=80",
                            Description = "43-inch Full HD Android Smart TV with frameless design.",
                            DiscountPercent = 13,
                            DiscountedPrice = 700m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Rangs 43 Inch Frameless Android TV",
                            Price = 800m,
                            Quantity = 30,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 5,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400\\u0026q=80\"}",
                            Colors = "black,blue",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
                            Description = "Premium ANC headphones with 30hr battery life and Hi-Res audio support.",
                            DiscountPercent = 3,
                            DiscountedPrice = 899m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "True Wireless Noise Cancelling Headphone",
                            Price = 930m,
                            Quantity = 100,
                            Rating = 5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400\\u0026q=80\"}",
                            Colors = "gray,black",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&q=80",
                            Description = "Apple MacBook Pro with M4 Pro chip, 16GB RAM, 512GB SSD.",
                            DiscountPercent = 10,
                            DiscountedPrice = 450m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Macbook Pro M4 Pro - 512/16GB",
                            Price = 500m,
                            Quantity = 15,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            Category = "Watches",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400\\u0026q=80\",\"orange\":\"https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400\\u0026q=80\"}",
                            Colors = "gray,orange",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400&q=80",
                            Description = "Aerospace-grade titanium Apple Watch Ultra with dual-frequency GPS.",
                            DiscountPercent = 10,
                            DiscountedPrice = 89m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Apple Watch Ultra",
                            Price = 99m,
                            Quantity = 40,
                            Rating = 3m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1611186871525-4de78d02cd32?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1611186871525-4de78d02cd32?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400\\u0026q=80\"}",
                            Colors = "gray,white",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1611186871525-4de78d02cd32?w=400&q=80",
                            Description = "Supercharged by M4. The thinnest, lightest Mac ever made.",
                            DiscountPercent = 14,
                            DiscountedPrice = 600m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "MacBook Air M4 chip, 16/256GB",
                            Price = 699m,
                            Quantity = 25,
                            Rating = 3.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400\\u0026q=80\"}",
                            Colors = "gray,blue",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
                            Description = "Stunning 24-inch 4.5K Retina display iMac powered by M4.",
                            DiscountPercent = 40,
                            DiscountedPrice = 333m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Apple iMac M4 24-inch 2025",
                            Price = 555m,
                            Quantity = 10,
                            Rating = 2.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1581993192008-63e896f4f744?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&q=80",
                            Description = "iPhone 16 Pro with A18 Pro chip, ProMotion display, 48MP camera.",
                            DiscountPercent = 33,
                            DiscountedPrice = 600m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "iPhone 16 Pro - 8/128GB",
                            Price = 899m,
                            Quantity = 60,
                            Rating = 5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400&q=80",
                            Description = "Dual vibration USB gamepad compatible with PC and Android.",
                            DiscountPercent = 52,
                            DiscountedPrice = 26m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Havit HV-G69 USB Gamepad",
                            Price = 54m,
                            Quantity = 200,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 4,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
                            Description = "200MP camera, titanium frame, built-in S Pen, 5000mAh battery, 12GB RAM.",
                            DiscountPercent = 15,
                            DiscountedPrice = 1099m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 1299m,
                            Quantity = 40,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 5,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80",
                            Description = "Industry-leading noise cancellation, 30hr battery, multipoint connection.",
                            DiscountPercent = 30,
                            DiscountedPrice = 279m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Sony WH-1000XM5 Wireless Headphones",
                            Price = 399m,
                            Quantity = 80,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 6,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80",
                            Description = "15.6-inch 3.5K OLED display, Intel Core i9, RTX 4060, 32GB RAM, 1TB SSD.",
                            DiscountPercent = 14,
                            DiscountedPrice = 1899m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Dell XPS 15 OLED - Intel i9 32GB",
                            Price = 2199m,
                            Quantity = 12,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=400\\u0026q=80\"}",
                            Colors = "gray,black",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80",
                            Description = "Ultra Retina XDR display, M4 chip, Apple Pencil Pro compatible.",
                            DiscountPercent = 10,
                            DiscountedPrice = 899m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Apple iPad Pro M4 - 11 inch 256GB",
                            Price = 999m,
                            Quantity = 25,
                            Rating = 4.9m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            Category = "Televisions",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1601944177325-f8867652837f?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1601944177325-f8867652837f?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1601944177325-f8867652837f?w=400&q=80",
                            Description = "Quantum HDR, Motion Xcelerator 120Hz, Object Tracking Sound, Alexa built-in.",
                            DiscountPercent = 23,
                            DiscountedPrice = 999m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Samsung 55 Inch QLED 4K Smart TV",
                            Price = 1299m,
                            Quantity = 18,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 8,
                            Category = "Watches",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400\\u0026q=80\"}",
                            Colors = "black,blue",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
                            Description = "AMOLED display, advanced running dynamics, up to 15-day battery.",
                            DiscountPercent = 16,
                            DiscountedPrice = 379m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Garmin Forerunner 265 GPS Running Watch",
                            Price = 449m,
                            Quantity = 35,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 7,
                            Category = "Home Appliances",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1527515637462-cff94aca2e0b?w=400\\u0026q=80\"}",
                            Colors = "black,blue",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
                            Description = "Laser detects invisible dust, HEPA filtration, 60min runtime.",
                            DiscountPercent = 13,
                            DiscountedPrice = 649m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Dyson V15 Detect Cordless Vacuum",
                            Price = 749m,
                            Quantity = 22,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 5,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1592840496694-26d035b52b48?w=400\\u0026q=80\"}",
                            Colors = "white,black",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&q=80",
                            Description = "Haptic feedback, adaptive triggers, built-in microphone, USB-C charging.",
                            DiscountPercent = 22,
                            DiscountedPrice = 69m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Sony DualSense PS5 Wireless Controller",
                            Price = 89m,
                            Quantity = 150,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 10,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400&q=80",
                            Description = "Google Tensor G3 chip, 50MP triple camera, 7 years of OS updates.",
                            DiscountPercent = 20,
                            DiscountedPrice = 799m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Google Pixel 8 Pro - 12GB 256GB",
                            Price = 999m,
                            Quantity = 30,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 9,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80",
                            Description = "8K DPI sensor, quiet clicks, MagSpeed electromagnetic scroll, USB-C.",
                            DiscountPercent = 20,
                            DiscountedPrice = 79m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Logitech MX Master 3S Wireless Mouse",
                            Price = 99m,
                            Quantity = 120,
                            Rating = 4.9m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 5,
                            Category = "Televisions",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=400&q=80",
                            Description = "Sony OLED 4K TV with Cognitive Processor XR and Google TV.",
                            DiscountPercent = 17,
                            DiscountedPrice = 1499m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Sony Bravia 55 inch 4K OLED TV",
                            Price = 1799m,
                            Quantity = 15,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 1,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400\\u0026q=80\"}",
                            Colors = "white,gray",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400&q=80",
                            Description = "Active Noise Cancellation, Adaptive Transparency, H2 chip.",
                            DiscountPercent = 20,
                            DiscountedPrice = 199m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Apple AirPods Pro 2nd Generation",
                            Price = 249m,
                            Quantity = 90,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 4,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=400\\u0026q=80\"}",
                            Colors = "gray,black",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80",
                            Description = "14.6 inch Dynamic AMOLED 2X, Snapdragon 8 Gen 2, 12GB RAM, S Pen.",
                            DiscountPercent = 17,
                            DiscountedPrice = 999m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Samsung Galaxy Tab S9 Ultra 14.6 inch",
                            Price = 1199m,
                            Quantity = 20,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 9,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&q=80",
                            Description = "Tenkeyless, hot-swappable switches, RGB LIGHTSYNC, tournament grade.",
                            DiscountPercent = 20,
                            DiscountedPrice = 119m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Logitech G Pro X Mechanical Gaming Keyboard",
                            Price = 149m,
                            Quantity = 60,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 10,
                            Category = "Watches",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400\\u0026q=80\"}",
                            Colors = "black,blue",
                            CreatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
                            Description = "Built-in GPS, heart rate monitoring, 7-day battery, Google Maps support.",
                            DiscountPercent = 19,
                            DiscountedPrice = 129m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Fitbit Charge 6 Fitness Tracker",
                            Price = 159m,
                            Quantity = 75,
                            Rating = 4.3m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 10,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400\\u0026q=80\"}",
                            Colors = "black,blue",
                            CreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80",
                            Description = "Intel Core Ultra 7, 16GB RAM, 1TB SSD, 2.8K OLED touchscreen.",
                            DiscountPercent = 13,
                            DiscountedPrice = 1299m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "HP Spectre x360 14 inch 2-in-1 Laptop",
                            Price = 1499m,
                            Quantity = 18,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 10,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=400\\u0026q=80\"}",
                            Colors = "gray,white",
                            CreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
                            Description = "3840x2160 IPS, 96W USB-C charging, HDR400, factory calibrated.",
                            DiscountPercent = 21,
                            DiscountedPrice = 549m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "LG UltraFine 27 inch 4K USB-C Monitor",
                            Price = 699m,
                            Quantity = 30,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 4,
                            Category = "Watches",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1434494878577-86c23bcb06b9?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400&q=80",
                            Description = "Rotating bezel, BioActive sensor, advanced health tracking, 40hr battery.",
                            DiscountPercent = 18,
                            DiscountedPrice = 329m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Samsung Galaxy Watch 6 Classic 47mm",
                            Price = 399m,
                            Quantity = 45,
                            Rating = 4.4m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 10,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400\\u0026q=80\",\"green\":\"https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=400\\u0026q=80\"}",
                            Colors = "black,green",
                            CreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&q=80",
                            Description = "Snapdragon 8 Gen 3, Hasselblad camera, 100W SuperVOOC, 5400mAh.",
                            DiscountPercent = 19,
                            DiscountedPrice = 649m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "OnePlus 12 16GB 512GB",
                            Price = 799m,
                            Quantity = 35,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 10,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80",
                            Description = "World-class noise cancellation, high-fidelity audio, 24hr battery.",
                            DiscountPercent = 24,
                            DiscountedPrice = 249m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Bose QuietComfort 45 Wireless Headphones",
                            Price = 329m,
                            Quantity = 55,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 10,
                            Category = "Home Appliances",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1527515637462-cff94aca2e0b?w=400\\u0026q=80\"}",
                            Colors = "white,black",
                            CreatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80",
                            Description = "4000Pa suction, LiDAR navigation, auto-empty base, mop function.",
                            DiscountPercent = 20,
                            DiscountedPrice = 399m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Xiaomi Robot Vacuum S10 Pro",
                            Price = 499m,
                            Quantity = 25,
                            Rating = 4.4m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 10,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400\\u0026q=80\"}",
                            Colors = "gray,blue",
                            CreatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&q=80",
                            Description = "13 inch PixelSense Flow touchscreen, Intel Evo i7, 16GB RAM.",
                            DiscountPercent = 13,
                            DiscountedPrice = 1399m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Microsoft Surface Pro 9 Intel i7 16GB",
                            Price = 1599m,
                            Quantity = 14,
                            Rating = 4.3m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 10,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1581993192008-63e896f4f744?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1581993192008-63e896f4f744?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=400\\u0026q=80\"}",
                            Colors = "white,gray",
                            CreatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1581993192008-63e896f4f744?w=400&q=80",
                            Description = "Glyph Interface, Snapdragon 8+ Gen 1, 50MP dual camera, 4700mAh.",
                            DiscountPercent = 17,
                            DiscountedPrice = 579m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Nothing Phone 2 12GB 256GB",
                            Price = 699m,
                            Quantity = 30,
                            Rating = 4.2m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 10,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80",
                            Description = "Intel i9 13th Gen, RTX 4070, 16GB DDR5, 1TB NVMe, 240Hz QHD.",
                            DiscountPercent = 16,
                            DiscountedPrice = 2099m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Asus ROG Strix G16 RTX 4070 Gaming Laptop",
                            Price = 2499m,
                            Quantity = 10,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 10,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
                            Description = "24.2MP APS-C sensor, 4K video, Dual Pixel CMOS AF II, Wi-Fi.",
                            DiscountPercent = 14,
                            DiscountedPrice = 599m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Canon EOS R50 Mirrorless Camera Body",
                            Price = 699m,
                            Quantity = 20,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 10,
                            Category = "Health & Sports",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80",
                            Description = "Performance Monitor 5, smooth chain drive, adjustable footrests.",
                            DiscountPercent = 15,
                            DiscountedPrice = 849m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Concept2 Model D Indoor Rowing Machine",
                            Price = 999m,
                            Quantity = 12,
                            Rating = 4.9m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 10,
                            Category = "Home Appliances",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1527515637462-cff94aca2e0b?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1527515637462-cff94aca2e0b?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1527515637462-cff94aca2e0b?w=400&q=80",
                            Description = "Auto-schedule, Energy Star, works with Alexa and Google Assistant.",
                            DiscountPercent = 18,
                            DiscountedPrice = 229m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Google Nest Learning Thermostat 4th Gen",
                            Price = 279m,
                            Quantity = 40,
                            Rating = 4.5m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 10,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&q=80",
                            Description = "30K DPI, 90hr battery, Focus Pro sensor, ultra-lightweight 64g.",
                            DiscountPercent = 20,
                            DiscountedPrice = 119m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Razer DeathAdder V3 Pro Wireless Mouse",
                            Price = 149m,
                            Quantity = 80,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 1,
                            Category = "Mobile & Tablets",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400\\u0026q=80\",\"blue\":\"https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400\\u0026q=80\"}",
                            Colors = "black,blue",
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&q=80",
                            Description = "A16 Bionic chip, 48MP main camera, Dynamic Island, USB-C.",
                            DiscountPercent = 13,
                            DiscountedPrice = 699m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "iPhone 15 6GB 128GB",
                            Price = 799m,
                            Quantity = 50,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 10,
                            Category = "Home Appliances",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1585515320310-259814833e62?w=400\\u0026q=80\"}",
                            Colors = "gray,black",
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400&q=80",
                            Description = "900W motor, 32oz cup, stainless steel blades, dishwasher safe.",
                            DiscountPercent = 22,
                            DiscountedPrice = 69m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "NutriBullet Pro 900W Personal Blender",
                            Price = 89m,
                            Quantity = 100,
                            Rating = 4.4m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 10,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400\\u0026q=80\"}",
                            Colors = "white,black",
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&q=80",
                            Description = "7 inch OLED screen, enhanced audio, 64GB storage, LAN port.",
                            DiscountPercent = 9,
                            DiscountedPrice = 319m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Nintendo Switch OLED Model White",
                            Price = 349m,
                            Quantity = 35,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 10,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1611186871525-4de78d02cd32?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&q=80",
                            Description = "Intel Core i7 13th Gen, 16GB RAM, 512GB SSD, 14 inch 2.8K OLED.",
                            DiscountPercent = 14,
                            DiscountedPrice = 1549m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Lenovo ThinkPad X1 Carbon Gen 11",
                            Price = 1799m,
                            Quantity = 12,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 10,
                            Category = "Watches",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400\\u0026q=80\",\"orange\":\"https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400\\u0026q=80\"}",
                            Colors = "black,orange",
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
                            Description = "1.62 inch AMOLED, 16-day battery, 150 workout modes, SpO2 monitoring.",
                            DiscountPercent = 29,
                            DiscountedPrice = 35m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Xiaomi Smart Band 8 Fitness Tracker",
                            Price = 49m,
                            Quantity = 200,
                            Rating = 4.2m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 5,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&q=80",
                            Description = "33MP BSI-CMOS sensor, 4K 60fps video, 759 phase-detect AF points.",
                            DiscountPercent = 12,
                            DiscountedPrice = 2199m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Sony Alpha A7 IV Full Frame Mirrorless",
                            Price = 2499m,
                            Quantity = 8,
                            Rating = 4.9m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 10,
                            Category = "Health & Sports",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&q=80",
                            Description = "Adjusts 5 to 52.5 lbs, replaces 15 sets of weights.",
                            DiscountPercent = 19,
                            DiscountedPrice = 349m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Bowflex SelectTech 552 Adjustable Dumbbells",
                            Price = 429m,
                            Quantity = 22,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 10,
                            Category = "Televisions",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1601944177325-f8867652837f?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1601944177325-f8867652837f?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1461151304267-38535e780c79?w=400\\u0026q=80\"}",
                            Colors = "black,gray",
                            CreatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1601944177325-f8867652837f?w=400&q=80",
                            Description = "QLED color technology, Dolby Vision IQ, 120Hz, Google TV built-in.",
                            DiscountPercent = 19,
                            DiscountedPrice = 649m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = false,
                            IsActive = true,
                            Name = "TCL 65 inch 4K QLED Smart TV",
                            Price = 799m,
                            Quantity = 20,
                            Rating = 4.4m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 10,
                            Category = "Home Appliances",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400\\u0026q=80\",\"gray\":\"https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1585515320310-259814833e62?w=400\\u0026q=80\"}",
                            Colors = "gray,black",
                            CreatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400&q=80",
                            Description = "Pressure cooker, slow cooker, rice cooker, steamer, sauté. 6 quart.",
                            DiscountPercent = 20,
                            DiscountedPrice = 79m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
                            Price = 99m,
                            Quantity = 80,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 10,
                            Category = "Games & Videos",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400\\u0026q=80\"}",
                            Colors = "black,white",
                            CreatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=400&q=80",
                            Description = "THX 7.1 Spatial Audio, TriForce 50mm drivers, HyperClear mic, 70hr battery.",
                            DiscountPercent = 20,
                            DiscountedPrice = 159m,
                            FastDelivery = false,
                            FreeDelivery = true,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Razer BlackShark V2 Pro Wireless Headset",
                            Price = 199m,
                            Quantity = 45,
                            Rating = 4.6m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 1,
                            Category = "Watches",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400\\u0026q=80\",\"orange\":\"https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400\\u0026q=80\"}",
                            Colors = "black,orange",
                            CreatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400&q=80",
                            Description = "S9 SiP chip, Double Tap gesture, Always-On Retina display, 18hr battery.",
                            DiscountPercent = 12,
                            DiscountedPrice = 379m,
                            FastDelivery = true,
                            FreeDelivery = true,
                            HasPromo = false,
                            IsActive = true,
                            Name = "Apple Watch Series 9 45mm GPS",
                            Price = 429m,
                            Quantity = 55,
                            Rating = 4.7m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 4,
                            Category = "Laptop & PC",
                            ColorImages = "{\"default\":\"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400\\u0026q=80\",\"white\":\"https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400\\u0026q=80\",\"black\":\"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400\\u0026q=80\"}",
                            Colors = "white,black",
                            CreatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DefaultImage = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400&q=80",
                            Description = "Dual QHD 5120x1440, 240Hz, 1ms, QLED, G-Sync + FreeSync, 1000R curve.",
                            DiscountPercent = 20,
                            DiscountedPrice = 1199m,
                            FastDelivery = false,
                            FreeDelivery = false,
                            HasPromo = true,
                            IsActive = true,
                            Name = "Samsung 49 inch Odyssey G9 Curved Monitor",
                            Price = 1499m,
                            Quantity = 10,
                            Rating = 4.8m,
                            ReviewCount = 0,
                            UpdatedAt = new DateTime(2025, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EcommerceApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EcommerceApi.Models.CartItem", b =>
                {
                    b.HasOne("EcommerceApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceApi.Models.Product", b =>
                {
                    b.HasOne("EcommerceApi.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EcommerceApi.Models.AppUser", "User")
                        .WithMany("Products")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceApi.Models.Review", b =>
                {
                    b.HasOne("EcommerceApi.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApi.Models.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceApi.Models.AppUser", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("EcommerceApi.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceApi.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
